apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-storage
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 200Gi
  storageClassName: "[CHANGEHERE]"
  accessModes:
    - ReadWriteOnce
